version: "3"

services:
    bot:
        build: .
        volumes:
            - ./data:/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TOKEN=${TOKEN}
            - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
