version: "3.8"

services:
    bot:
        build: .
        volumes:
            - ./data:/data
        environment:
            - TOKEN=${TOKEN}
            - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}